import type { GameSpec } from "../../contracts/gamespec";

export type AdventureKind = "observatory" | "cell" | "archive" | "station";

export interface AdventureChapter {
  id: string;
  name: string;
  objective: string;
  apparatus: string;
  briefing: string;
  discovery: string;
  consequence: string;
}

export interface AdventureCampaign {
  id: string;
  kind: AdventureKind;
  title: string;
  subtitle: string;
  role: string;
  companion: string;
  companionRole: string;
  intro: string;
  finale: string;
  chapters: AdventureChapter[];
}

function chapter(id: string, name: string, objective: string, apparatus: string, briefing: string, discovery: string, consequence: string): AdventureChapter {
  return { id, name, objective, apparatus, briefing: briefing.replace(/^(Iona|Tavi|Neri|Mara|Pax): /, ""), discovery, consequence };
}

const observatory: AdventureCampaign = {
  id: "trig_demo_001", kind: "observatory", title: "The Last Light of Meridian",
  subtitle: "Wake an astronomical city before its navigation beacon goes dark.",
  role: "Apprentice skywright", companion: "Iona", companionRole: "Keeper of Meridian's star instruments",
  intro: "Meridian's sea lantern has stopped turning. Ships wait beyond the reef while the city's six instruments drift out of agreement. Iona brings you into the abandoned observatory: restore its measuring court, synchronize its machinery, then carry a stable signal to the crown beacon. The instruments respond to mathematical relationships, not force.",
  finale: "The crown lens turns with a steady rhythm. Light travels from the measuring court through every restored chamber and sweeps across the reef. Iona records your calibrations in the keeper's ledger; the returning ships can read Meridian's bearing again. Your field notes preserve the difference between angle, amplitude, and period for the next skywright.",
  chapters: [
    chapter("e1_radians", "Act I · Arc Survey Court", "Locate the requested angle on the survey rail to aim the first light collector.", "Unrolled circle survey rail", "Iona: The circular rim has been laid out as a straight measuring rail. Inspect the marks, collect the survey note, and give the collector an angle it can follow.", "Survey note: Radians compare arc length with radius. Unrolling a circle preserves the fraction of a turn; the rail is a measuring instrument, not a different kind of angle.", "The collector rotates toward the sky. A turquoise beam reaches the shutter chamber and illuminates its stalled rings."),
    chapter("e2_period", "Act I · Shutter Ring Chamber", "Calibrate one complete cycle so the shutters pass the survey beam together.", "Coupled sine shutter rings", "Iona: These rings must return to their starting positions together. Watch a full oscillation before setting the interval; a faster ring does not need more time.", "Maintenance note: The coefficient inside sine changes how quickly the cycle repeats. Period measures horizontal repetition rather than the height of a swing.", "The shutters settle into rhythm. Their moving shadows clear the passage into the lens conservatory."),
    chapter("e3_amplitude", "Act II · Lens Conservatory", "Identify the faulty amplitude claim before the lens lift is commissioned.", "Three brass calibration plaques", "Iona: One plaque would make the keeper adjust the wrong control. Compare each claim with the moving light trace and flag the misleading instruction.", "Lensmaker's note: Vertical stretch changes the trace's distance from its midline. A taller trace alone does not tell you how long a cycle takes.", "The incorrect plaque is marked for repair. The lens lift rises safely and carries the beam to the twin-angle gallery."),
    chapter("e4_solve", "Act II · Twin-Angle Gallery", "Reconstruct a valid solution procedure so both mirror mounts receive their bearings.", "Ordered mirror-alignment planks", "Iona: Two mirrors can share the same vertical coordinate. Build the reasoning in order and set aside the plank that would hide a valid bearing.", "Gallery sketch: A sine value can correspond to more than one angle in a full turn. The domain determines which mirror positions belong in the calibration.", "Both mirror mounts engage. Their reflected beams meet over the treasury door, revealing the older frequency records."),
    chapter("e5_period_review", "Act III · Frequency Treasury", "Audit the stored period claims before reconnecting the crown drive.", "Archived oscillator plaques", "Iona: The treasury kept spare calibrations, including one bad record. Use what the shutters taught you to check the period claims before sending power upward.", "Treasury note: Recheck the inner coefficient when comparing oscillators. The amplitude dial and the period dial describe different properties of the same trace.", "The keeper's records are corrected. A copper drive shaft begins turning and supplies the crown beacon with a reliable timing signal."),
    chapter("e6_boss", "Act III · Crown Beacon", "Match the crown oscillator's period to restore the sea lantern.", "Great sine beacon regulator", "Iona: The crown swings farther than the shutters, but its timing still comes from the inner coefficient. Read the presented oscillator and synchronize the final regulator.", "Crown log: A large vertical swing can distract a calibrator. Separate amplitude from cycle length before committing a timing setting.", "The regulator locks. The crown lens lifts into the night and sends a continuous navigation sweep across the harbor."),
  ],
};

const platformer: AdventureCampaign = {
  ...observatory, id: "trig_platformer_001", title: "Meridian's Skywalk",
  subtitle: "Carry a light signal across the observatory's suspended terraces.",
  role: "Skywalk signal courier", companion: "Tavi", companionRole: "Engineer of the suspended observatory",
  intro: "A broken cable has isolated Meridian's upper beacon. Tavi has rigged temporary terraces around six dormant instruments, but each crossing depends on a stable calibration. Travel the skywalk, recover the engineer's notes, and restore the signal relay at every landing. Falls return you to safe ground; careful observation matters more than speed.",
  finale: "A line of lamps joins the terraces from the survey landing to the crown. Tavi opens the maintenance skywalk for the harbor crew, and your signal reaches the restored beacon. The journey ends with a safe route through the observatory and a record of the mathematics that made its machines agree.",
  chapters: [
    chapter("e1_radians", "Act I · Survey Landing", "Set the survey angle to direct a guide light across the first gap.", "Skywalk arc rail", "Tavi: The landing's rail is a circle laid flat. Read its landmarks, recover the courier note, then aim the guide light before taking the crossing.", "Courier note: A fraction of a full turn stays the same when the rim becomes a line. Position on the rail represents angle around the original circle.", "A guide lamp lights the opposite terrace. The first crossing now leads to the shutter landing."),
    chapter("e2_period", "Act I · Shutter Landing", "Synchronize the oscillating shutter signal that marks the next safe landing.", "Terrace sine timing drum", "Tavi: Wait and watch the drum repeat. Set one full period so the terrace lights signal together; the path is readable once their rhythm is stable.", "Timing card: Increasing the inner wave coefficient produces more cycles over the same interval. The repeat time changes even when the swing height does not.", "The terrace lamps pulse in agreement. Their signal exposes the route to the lens gantry."),
    chapter("e3_amplitude", "Act II · Lens Gantry", "Flag the false amplitude instruction before restarting the elevated lens carriage.", "Gantry calibration plaques", "Tavi: The carriage's safety instructions disagree. Inspect all three claims and identify the one that confuses vertical reach with horizontal timing.", "Gantry note: Amplitude is the size of a vertical departure from the midline. Treating it as cycle duration would miscalibrate the signal.", "The unsafe instruction is removed. The lens carriage returns to service and illuminates the mirror bridge."),
    chapter("e4_solve", "Act II · Mirror Bridge", "Order the mirror-solving procedure to aim both ends of the bridge signal.", "Bridge bearing sequence board", "Tavi: The bridge has two receivers. Assemble the solution steps and reject the extra plank so neither valid angle disappears from the route plan.", "Bridge sketch: Equal sine values can occur on opposite sides of the circle. Restrict solutions to the stated interval before recording the bearings.", "Twin receivers glow at the bridge ends. The signal continues into the high treasury landing."),
    chapter("e5_period_review", "Act III · Treasury Landing", "Verify the frequency archive before powering the final ascent lamps.", "Skywalk oscillator archive", "Tavi: One old timing label is wrong. Compare the stored claims with your shutter calibration, then authorize the cable connection.", "Cable log: Period follows the rate of repetition. A claim that follows the outside amplitude coefficient cannot set the ascent's timing.", "The archive relays a checked timing signal. Lamps trace the final ascent to the crown platform."),
    chapter("e6_boss", "Act III · Crown Platform", "Synchronize the great oscillator and deliver the skywalk signal to the sea beacon.", "Suspended beacon regulator", "Tavi: You've brought the signal this far. The final trace has a broad swing; focus on the parameter that controls repetition and lock its period.", "Final delivery note: Vertical scale and horizontal repetition remain independent even in a large machine. Read both before setting either control.", "The upper relay catches your signal. The beacon rotates and every terrace lamp stays lit for the returning maintenance crew."),
  ],
};

const cell: AdventureCampaign = {
  id: "cell_demo_001", kind: "cell", title: "The Living Sanctuary",
  subtitle: "Restore the transport systems of a luminous model cell.",
  role: "Microscale transport steward", companion: "Neri", companionRole: "Sanctuary membrane technician",
  intro: "The sanctuary is a scientific model built as a walkable living garden. Its membrane admits the wrong cargo, its water chambers are unbalanced, and its energy pumps have lost their instructions. Neri needs a transport steward to repair the boundary, stabilize the interior, and reconnect the final cargo network. Each restoration models a cell process; the garden's lights make the consequences visible.",
  finale: "Water chambers settle, selective gates glow, and the pump circuit resumes its measured exchange. Neri opens the nucleus conservatory as the cargo network begins moving again. The sanctuary is stable because its different transport routes now have different jobs, recorded in your field journal.",
  chapters: [
    chapter("e1_bilayer", "Act I · Phospholipid Grove", "Identify the incorrect membrane description so the outer boundary can be repaired.", "Bilayer inspection plaques", "Neri: Look closely at the wall's paired layers. One maintenance plaque contradicts their structure; mark it before we reseal the grove.", "Boundary note: The arrangement of phospholipids creates a selective boundary. A membrane's structure explains why different molecules need different routes.", "The wall seals into two coherent layers. Its glowing boundary guides cargo toward the selective gatehouse."),
    chapter("e2_selectivity", "Act I · Selective Gatehouse", "Route each molecule through an appropriate crossing pathway.", "Bilayer and protein cargo sorter", "Neri: Cargo is piling up at the boundary. Sort by the molecule's properties and the available pathways instead of opening every gate for every traveler.", "Gatehouse manifest: Small nonpolar cargo and cargo needing a transport protein do not cross in the same way. Selectivity depends on both cargo and membrane.", "Traffic separates into visible routes. The cleared gatehouse releases the dye chamber for inspection."),
    chapter("e3_diffusion", "Act I · Dye Atrium", "Reject the false explanation of the spreading dye cloud.", "Concentration inspection windows", "Neri: Watch the dye cloud spread without a motor. Inspect the three explanations and flag the one that fails to describe the gradient-driven net movement.", "Dye record: Individual particles move randomly while the population has net movement down a concentration gradient. Spreading does not require a purposeful particle.", "The atrium's concentration lamps equalize. A transparent channel opens toward the water reservoir."),
    chapter("e4_osmosis", "Act I · Water Reservoir", "Check the predictions for a cell surrounded by salty water.", "Osmosis observation tank", "Neri: The reservoir's predictions disagree about water. Read the conditions in the instrument and identify the claim that would make our water valves respond incorrectly.", "Reservoir note: Osmosis concerns water crossing a selectively permeable boundary. Compare the solutions on both sides before predicting its net direction.", "The faulty valve instruction is isolated. The reservoir sends a measured water supply to the tonicity nursery."),
    chapter("e5_tonicity", "Act II · Tonicity Nursery", "Label each passing cell's solution relationship to stabilize the nursery displays.", "Cell-and-solution labeling channel", "Neri: Each tank pairs a cell with its surroundings. Use their relative conditions to label the relationship; a solution name needs something to compare with.", "Nursery card: Tonicity describes the effect of the surrounding solution on a cell's water balance. It is a relationship rather than an absolute label for all cells.", "The nursery tanks gain legible condition labels. Their indicator lights reveal which transport cases need review next."),
    chapter("e6_facilitated", "Act II · Protein Arcade", "Separate passive transport from energy-driven transport.", "Protein passage classification console", "Neri: A protein gate is not proof that ATP is spent. Inspect each cargo case for gradient direction and energy use, then route it to the correct circuit.", "Arcade note: Facilitated diffusion uses proteins while remaining passive. Crossing against a gradient requires an energy source rather than merely a protein doorway.", "Passive channels and powered pumps receive separate signals. The arcade stops wasting pump power and reconnects the energy gallery."),
    chapter("e7_active", "Act II · ATP Gallery", "Identify the false active-transport instruction before restoring the pumps.", "Energy pump maintenance plaques", "Neri: The pumps have power but contradictory instructions. Compare the claims with gradient direction and energy requirements before restarting their cycle.", "Power log: Active transport moves cargo against its gradient using energy. The distinction concerns direction and energy, not whether a membrane is involved.", "Pump pistons begin their coordinated strokes. The gallery supplies energy to the ion exchange engine."),
    chapter("e8_pump", "Act II · Ion Exchange Engine", "Reconnect each sodium-potassium pump cycle component with its value.", "Ion-cycle wiring board", "Neri: Every connector belongs to a specific part of the cycle. Link the labels carefully so the engine exchanges the correct cargo on the correct side.", "Engine diagram: Sodium-potassium exchange has a defined direction and count for each ion. A cycle is an organized sequence, not equal cargo moving both ways.", "The exchange engine pulses in its prescribed pattern. Two colored ion streams light the passage to the reservoir audit."),
    chapter("e9_osmosis_review", "Act III · Reservoir Audit", "Predict net water movement for each reviewed cell condition.", "Water-direction review channel", "Neri: The restored system needs a final water audit. Compare each cell with its surroundings and name the direction the displayed conditions imply.", "Audit sheet: Predict water movement from the relative solution conditions. Rechecking several cases tests the relationship rather than memorizing a single tank.", "Directional arrows appear across the water network. Stable pressure allows the bulk cargo dock to reopen."),
    chapter("e10_bulk", "Act III · Vesicle Dock", "Reconstruct the sequence that brings a large particle into the cell.", "Endocytosis sequence cradle", "Neri: This cargo cannot slip through an ordinary channel. Assemble the inward vesicle sequence and remove the plank that describes a different trip.", "Dock sketch: Membrane wrapping produces a vesicle for inward bulk transport. Inward uptake and outward release use different directions in their sequences.", "A vesicle closes around the cargo and moves inward. The dock connects its route to the final transport exchange."),
    chapter("e11_boss", "Act III · Nucleus Conservatory", "Sort the complete cargo manifest by its membrane crossing mechanism.", "Sanctuary transport dispatch table", "Neri: All the repaired pathways converge here. Assign each cargo case to its proper mechanism so the conservatory receives supplies without losing its boundary.", "Dispatch note: Cargo properties, gradients, proteins, energy, and particle size jointly determine a transport route. A working cell coordinates several mechanisms.", "The dispatch lights show a complete network. The conservatory doors open as water, ions, and bulk cargo move through their restored routes."),
  ],
};

const archive: AdventureCampaign = {
  id: "history_mystery_001", kind: "archive", title: "The Unfinished Public Record",
  subtitle: "Reconstruct an evidence-based account of the civil rights movement.",
  role: "Community archive researcher", companion: "Mara Ellis", companionRole: "Fictional historian and archive editor",
  intro: "A community archive is preparing a public reading room, but its civil rights exhibit has mixed dates, misleading labels, and unsupported causal claims. Mara Ellis, a fictional historian, asks you to reconstruct the record from the supplied historical evidence. This is a simplified classroom account, not a complete history of the movement. Establish the early challenges to segregation, trace organizing and institutional responses, then defend a careful explanation of voting rights legislation. Your work repairs an exhibit; it does not reenact suffering or place invented words in historical figures' mouths.",
  finale: "The reading room opens with corrected labels, visible source distinctions, and a causal account visitors can examine. Mara files your research notes beside the exhibit rather than presenting its interpretation as the only possible story. The final board recognizes organizing, repression, public attention, and institutional action while keeping each historical claim tied to the supplied evidence.",
  chapters: [
    chapter("e1_brown", "Act I · Legal Reading Desk", "Identify the false Brown v. Board label in the opening exhibit.", "Court-decision label review desk", "Mara: Begin with the claims attached to this decision. Compare them with the supplied evidence and mark the label that would mislead a visitor about the ruling.", "Research note: A court ruling and its implementation are different historical questions. Establish precisely what the evidence supports before describing its consequences.", "The opening case receives corrected labels. The archive can connect the legal challenge with the next organizing file."),
    chapter("e2_montgomery", "Act I · Boycott Timeline Room", "Reconstruct the Montgomery boycott sequence and exclude the unrelated event.", "Chronology strip and event cards", "Mara: These cards mix a sequence with a distractor. Arrange the supported events in order so visitors can follow sustained organizing rather than a single isolated moment.", "Timeline note: Chronology constrains an explanation. Identify what began, sustained, and followed an action before connecting it to wider change.", "The boycott timeline lights from left to right. Its dated entries make room for the school desegregation file."),
    chapter("e3_little_rock", "Act I · Federal Response Cabinet", "Examine the institutional response to the exclusion of the Little Rock Nine.", "Prediction-and-evidence cabinet", "Mara: Read the situation as it stood in September 1957, make your prediction, then inspect the revealed response. Distinguish a prediction from the historical evidence.", "Cabinet note: Federal and state institutions could take opposing actions. Record who acted and what authority they exercised instead of treating government as one actor.", "The cabinet opens onto the documented response. A clear institutional label links the first act to the organizing gallery."),
    chapter("e4_sit_ins", "Act II · Student Organizing Gallery", "Correct the misleading label about the Greensboro sit-ins.", "Sit-in exhibit claim plaques", "Mara: Test each plaque against the supplied record. The exhibit should make the students' method and the setting legible without adding details the evidence does not establish.", "Gallery note: Specific tactics matter when explaining a movement. Describe the supported action before generalizing about its significance.", "The corrected display centers student organizing. A route marker leads visitors into the interstate travel files."),
    chapter("e5_freedom_rides", "Act II · Interstate Dispatch Room", "Connect the supported events and consequences of the Freedom Rides.", "Event-and-response linkage board", "Mara: The dispatches have lost their connections. Link the events to their supported consequences; close dates alone are not enough to establish a causal link.", "Dispatch note: Causal explanations name an action, a response, and a mechanism connecting them. Check the evidence at each link rather than guessing from order alone.", "The dispatch board displays a traceable sequence of responses. Its completed links lead to the Birmingham newsroom."),
    chapter("e6_birmingham", "Act II · Birmingham Newsroom", "Reconstruct the evidenced chain of protest, response, and public attention.", "Birmingham causal document board", "Mara: Connect the supplied pieces with care. Our display must acknowledge repression and organizing through evidence, without turning either into a spectacle.", "Newsroom note: Public attention can mediate between local events and national pressure. Keep the mechanism visible instead of claiming that one image alone explains change.", "The newsroom board gains a readable causal chain. The archive's attention map opens the March on Washington gallery."),
    chapter("e7_march", "Act II · March Contributions Gallery", "Match each named participant to the contribution supported by the record.", "Participant-and-role index", "Mara: This index has separated names from roles. Reconnect them using the supplied information so the exhibit recognizes contributions accurately and avoids invented quotations.", "Index note: A movement includes distinct organizing, speaking, and institutional roles. Attribution requires evidence about the particular person and contribution.", "The participant index is restored. Visitors can follow the gallery into the legislation comparison room."),
    chapter("e8_cra", "Act II · Legislation Comparison Room", "File the provisions under the act that established them.", "Two-act provision filing desk", "Mara: Similar purposes do not make these laws interchangeable. Sort the provisions under their correct acts before we print the exhibit's legislative summary.", "Legislation note: Identify what each law addresses and how it operates. Keeping provisions separate prevents a broad story of progress from erasing legal distinctions.", "The filing desk produces two distinct legislative panels. The corrected comparison sets up the Selma chronology."),
    chapter("e9_selma", "Act III · Selma Chronology Alcove", "Put the supported events in date order and remove the misplaced card.", "Dated event reconstruction rail", "Mara: Restore the dates before interpreting the sequence. One card belongs elsewhere; excluding it protects this account from a plausible but unsupported shortcut.", "Alcove note: A sequence needs a defined scope as well as correct dates. An event's importance elsewhere does not make it part of every local chronology.", "The Selma rail becomes a coherent dated record. Its restored sequence directs researchers toward the source workshop."),
    chapter("e10_sources", "Act III · Source Workshop", "Classify the documents as primary or secondary sources about the movement.", "Document provenance sorting table", "Mara: Examine each document's relationship to the events. Classify the source type without assuming that being contemporary automatically makes every claim reliable.", "Workshop note: Source type and source reliability are separate judgments. Context, authorship, purpose, and relation to the research question guide how evidence is used.", "The documents receive visible provenance labels. The workshop releases a checked evidence set for the synthesis board."),
    chapter("e11_causation", "Act III · National Change Board", "Link the supplied developments from Birmingham to voting rights legislation.", "Multi-event causal synthesis board", "Mara: Build the larger chain from the evidence you have reviewed. Preserve the intermediate connections; the board should explain a process rather than imply an inevitable ending.", "Synthesis note: Historical change involves connected developments and choices. A causal chain needs supported intermediate links, not simply its first and last dates.", "The national board joins the earlier rooms into a supported explanation. Its connected record unlocks the editorial desk."),
    chapter("e12_boss", "Act III · Editorial Evidence Desk", "Use the clues to defend the explanation for the timing of the Voting Rights Act.", "Claim-elimination and evidence desk", "Mara: Review every clue and reject explanations that cannot account for the supplied record. Choose the supported explanation, then let the debrief show the evidence behind the exhibit.", "Editor's note: A persuasive historical explanation accounts for timing as well as outcome. Elimination should test claims against evidence rather than confidence or dramatic appeal.", "The final explanation is attached to its evidence. The reading-room lamps turn on and the unfinished exhibit becomes a public record visitors can question and inspect."),
  ],
};

const station: AdventureCampaign = {
  id: "wave2_smoke_001", kind: "station", title: "The Nine Systems of Aurora",
  subtitle: "Bring a multidisciplinary research station back into balance.",
  role: "Research station systems apprentice", companion: "Pax", companionRole: "Aurora's maintenance coordinator",
  intro: "Aurora's research station has entered a safe shutdown. Its terrain scanner, balances, reactor, resource ledger, translation lab, and control logic each preserve part of the recovery plan. Pax asks you to restore the nine systems in three passes: inspect the physical foundations, recover the working processes, then validate the control record. Different tools need different forms of reasoning, and each repaired system supplies the next.",
  finale: "Aurora's copper conduits glow from the ridge scanner to the control tower. The reactor has a balanced recipe, the ledger accounts for its supplies, and the controller follows a checked sequence. Pax reopens the research floor with your field journal as its recovery manual. The station works because measurements, conservation, translation, and reasoning agree at their boundaries.",
  chapters: [
    chapter("w1_slope", "Act I · Ridge Survey Deck", "Identify the steepest terrain with the tangent scanner.", "Local-slope terrain scanner", "Pax: The supply route crosses this ridge. Sweep the scanner along the displayed terrain and mark the point where local steepness is greatest.", "Survey sheet: Local slope describes change near a point. A high elevation is not necessarily a steep segment; the tangent measures the relevant property.", "The survey beacon marks the critical ridge section. Its map gives the balance chamber a safe equipment route."),
    chapter("w2_equation", "Act I · Counterweight Chamber", "Apply equivalent operations until the unknown counterweight is isolated.", "Two-pan algebra balance", "Pax: Both pans must stay equivalent at every step. Apply the same operation to each side until the unknown is alone and the lift can be calibrated.", "Balance note: An equation states equality. Transforming both sides consistently preserves that relationship while revealing the unknown.", "The lift finds its calibrated counterweight. It carries stored atom canisters into the reactor laboratory."),
    chapter("w3_chem", "Act I · Atom Conservation Reactor", "Balance the reaction coefficients so every atom is accounted for.", "Atom-token reaction mixer", "Pax: The reactor cannot start with an unbalanced manifest. Set the coefficients while keeping each substance's formula intact and compare atom counts on both sides.", "Reactor note: Chemical balancing conserves each element. Coefficients change the number of molecules; altering a formula would change the substance itself.", "The reactor accepts a conserved recipe. Its steady power wakes the resource accounting office."),
    chapter("w4_ledger", "Act II · Resource Accounting Office", "Balance the monthly resource ledger so the station can authorize supplies.", "Income-and-outflow ledger console", "Pax: Reactor power is available, but supplies need an accountable budget. Record the displayed inflows and outflows until every dollar is explained.", "Office note: A ledger is a conservation record for resources. Follow the sign and role of each entry instead of treating every amount as interchangeable.", "The office authorizes an accounted supply shipment. Labeled reagent crates reach the translation laboratory."),
    chapter("w5_encode", "Act II · Translation Laboratory", "Translate the displayed mRNA codons using the supplied mapping table.", "Codon-to-amino-acid translation reader", "Pax: The lab's label maker accepts a sequence, not individual bases. Read each codon in order and use the displayed table to reconstruct its output.", "Lab note: A mapping preserves input order while changing representation. Codons are read as triplets; the table supplies the meaning of each triplet.", "The label maker prints the translated sequence. The verified labels reconnect the adjacent function testing bench."),
    chapter("w6_machine", "Act II · Function Testing Bench", "Infer the consistent transformation and predict the queried output.", "Input-output function tester", "Pax: The bench has forgotten its rule but kept examples. Check a proposed transformation against every pair before using it on the new input.", "Bench note: A function applies a consistent rule. Several examples constrain an inference more strongly than a pattern guessed from one pair.", "The tester accepts the prediction and restores its transformation record. The control workshop receives checked output labels."),
    chapter("w7_trace", "Act III · Control Logic Workshop", "Trace each instruction to determine the controller's printed output.", "Stepwise variable-state console", "Pax: Read the controller line by line. Track updates, branches, and list positions so the final print record reflects the actual execution order.", "Control note: Assignment updates a stored state. A later instruction sees the current value, and list indexing must follow the convention shown in the program.", "The console produces a verified execution trace. Its sequence restores the memory station's status display."),
    chapter("w8_recall", "Act III · Calibration Memory Station", "Retrieve the displayed trigonometric facts to rebuild the calibration index.", "Returning-prompt memory relay", "Pax: The relay needs recalled definitions to index the instruments. Missed prompts return; use the displayed hints and keep working until the record is complete.", "Memory card: Retrieval checks whether a relationship can be produced, rather than merely recognized. Repeated attempts can repair a missing calibration entry.", "The calibration index fills with checked entries. Its complete record supplies the final control tower audit."),
    chapter("w9_boss", "Act III · Control Tower Audit", "Complete the statement separating vertical stretch from cycle length.", "Contextual calibration statement desk", "Pax: The last recovery instruction has a missing term. Use the surrounding mathematical relationship to complete it before authorizing station restart.", "Audit note: A statement's context constrains its missing concept. Distinguishing vertical scale from horizontal repetition prevents the controller from coupling unrelated settings.", "The final instruction is restored. Aurora leaves safe shutdown and its research floor reopens with every subsystem accounted for."),
  ],
};

const campaigns: Record<string, AdventureCampaign> = {
  [observatory.id]: observatory,
  [platformer.id]: platformer,
  [cell.id]: cell,
  [archive.id]: archive,
  history_demo_001: { ...archive, id: "history_demo_001" },
  [station.id]: station,
};

/** Authored fixture presentation only. Unknown or drifted specs keep the generated-game host. */
export function getAdventureCampaign(spec: GameSpec): AdventureCampaign | null {
  const campaign = campaigns[spec.id];
  if (!campaign || spec.encounters.length !== campaign.chapters.length) return null;
  const byId = new Map(campaign.chapters.map((entry) => [entry.id, entry]));
  if (new Set(spec.encounters.map((entry) => entry.id)).size !== campaign.chapters.length) return null;
  if (spec.encounters.some((entry) => !byId.has(entry.id))) return null;
  // Preserve fixture ordering and give each caller an independent presentation snapshot.
  return { ...campaign, chapters: spec.encounters.map((entry) => ({ ...byId.get(entry.id)! })) };
}
