"use client";

import { useId, useState, type PointerEvent } from "react";
import type { Current } from "../runner/encounter-runner";
import type { AdventureChapter, AdventureKind } from "./campaigns";
import "./studio.css";

export interface LearningStudioProps {
  kind: AdventureKind;
  current: Current;
  chapter: AdventureChapter;
  guidance: "supported" | "light" | "independent";
  onDone(): void;
}
type Lesson = { title: string; principle: string; steps: [string, string, string]; prediction: string; choices: [string, string, string]; correct: number; explanation: string; visual?: "circle" | "wave" | "membrane" };
const lesson = (title: string, principle: string, steps: Lesson["steps"], prediction: string, choices: Lesson["choices"], correct: number, explanation: string, visual?: Lesson["visual"]): Lesson => ({ title, principle, steps, prediction, choices, correct, explanation, visual });
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};

/** Lesson examples are authored independently of encounter content and grading data. */
function chooseLesson(kind: AdventureKind, current: Current, chapter: AdventureChapter): Lesson {
  const text = `${chapter.id} ${chapter.objective} ${chapter.discovery}`.toLowerCase();
  const view = record(current.view);
  if (current.mode.id === "number_line" || /radian|mirror|bearing/.test(text)) return lesson("A turn becomes a measurement", "An angle in radians is arc length divided by radius: θ = s/r. On the unit circle, the endpoint is (cos θ, sin θ): horizontal position first, vertical position second.", ["Start with a training circle of radius 2 m. A quarter-turn traces an arc of π m, so θ = π/2 radians.", "Drag the dial: its radius turns counterclockwise from the right. The dotted projections show actual horizontal and vertical coordinates on a unit circle.", "At 150°, the reference angle is 30°: the point is left of the origin and above it. Thus cos is negative and sin is positive. At 30° and 150°, the same height gives the same sine; always check the allowed angle interval."], "A training rim doubles its radius and keeps the same angle. What happens to its arc length?", ["It doubles", "It stays unchanged", "It halves"], 0, "The arc doubles because s = rθ. Its fraction of a full turn and its angle stay the same. Use the apparatus landmarks to transfer that fraction to the rail.", "circle");
  if (current.mode.id === "oscillator" || /amplitude|period|frequency|oscillator|vertical stretch|trigonometric/.test(text)) return lesson("Read the motion, one control at a time", "For y = A sin(bt + c) + d, amplitude is |A|, period is 2π/|b|, phase shift is −c/b, and midline is d (b ≠ 0). A and d change vertical position; b changes repetition; c changes horizontal alignment.", ["Our training signal begins at y = 2 sin(t) + 1. It swings from −1 to 3, around the midline y = 1, and repeats every 2π time units.", "Move A from 2 to 3. The swing grows, but the distance between repeating peaks stays the same. Now increase b: more cycles fit into the same time interval.", "Try c and d separately. c shifts the trace horizontally without changing its period; d moves its center vertically. The probe shows the calculated value at your selected time. The same parameter roles apply to cosine."], /amplitude|vertical stretch/.test(text) ? "On a training signal, A doubles while b, c, and d stay fixed. Which property changes?" : "On a training signal, b doubles while A, c, and d stay fixed. What happens to the period?", /amplitude|vertical stretch/.test(text) ? ["The period doubles", "The amplitude doubles", "The midline doubles"] : ["It doubles", "It stays unchanged", "It halves"], /amplitude|vertical stretch/.test(text) ? 1 : 2, /amplitude|vertical stretch/.test(text) ? "Amplitude is |A|, so it doubles. Period depends on b, and the midline depends on d. Inspect the relevant control when evaluating a calibration claim." : "T = 2π/|b|: doubling the rate halves the repeat time. Compare two equivalent points in successive cycles, rather than reading the height of a peak.", "wave");
  if (kind === "observatory" && /sine|sinus|solution|quadrant|reference angle/.test(text)) return lesson("Find every direction a signal can point", "Solving a sine condition means finding every angle whose unit-circle height matches the requested value. Use the reference angle, the sign in each quadrant, and the interval to list all valid directions.", ["A training beacon reports sin θ = 1/2 during one revolution, 0 ≤ θ < 2π. The reference angle is π/6, because a point at π/6 has height 1/2.", "Sine is positive above the horizontal axis, so there are two matching points in the interval: quadrant I at π/6 and quadrant II at π − π/6 = 5π/6.", "Check the interval endpoints and the original condition. Neither 0 nor 2π has height 1/2. If the measured value were negative, reflect the same reference angle into quadrants III and IV instead."], "A two-sided sensor reports sin θ = −1/2 for one turn, 0 ≤ θ < 2π. Which pair contains every matching direction?", ["π/6 and 5π/6", "7π/6 and 11π/6", "π/3 and 5π/3"], 1, "Sine is negative below the horizontal axis, in quadrants III and IV. With reference angle π/6, the directions are π + π/6 = 7π/6 and 2π − π/6 = 11π/6. Verify both satisfy the value and the stated interval.", "circle");
  if (kind === "cell") {
    if (/osmos|tonicity|water/.test(text)) return lesson("Water balance under the microscope", "Osmosis is net water movement through a selectively permeable membrane. For a membrane permeable to water but not the compared solute, water moves toward the side with the higher solute concentration. Tonicity depends on nonpenetrating solutes relative to a cell.", ["Training tank: the cell contains 6 units of nonpenetrating solute per volume; the surrounding fluid contains 2. Water can cross, but this solute cannot.", "Compare equal volumes on both sides. The cell side has more solute, so net water movement is inward. The surrounding solution is hypotonic relative to this cell.", "Reverse the two concentrations: net water movement is outward, and the cell tends to shrink. Equal effective concentrations give no net water movement; molecules still cross both ways."], "A training cell and its surroundings have equal nonpenetrating-solute concentrations. What should the water-direction display show?", ["Water stops moving entirely", "No net movement", "Only inward movement"], 1, "Water molecules still move both ways, but equal opposing flows mean no net movement. Compare the two sides before selecting a water-direction label.", "membrane");
    if (/bulk|vesicle|endocyt/.test(text)) return lesson("A membrane can carry a whole parcel", "Large cargo can enter by endocytosis: membrane surrounds cargo, closes into a vesicle, and carries it inward. Exocytosis releases cargo when an internal vesicle fuses with the membrane.", ["Training cargo is a large particle outside the cell, too large for a channel. The membrane bends around it.", "The membrane pocket closes, producing an enclosed vesicle inside the cell. Follow cargo location, not just the shape of the membrane.", "For outward delivery, an internal vesicle instead fuses with the boundary and releases its contents. This reverses the delivery direction, not simply the order of every uptake step."], "An internal vesicle fuses with the boundary and releases a parcel outside. Which process fits?", ["Endocytosis", "Simple diffusion", "Exocytosis"], 2, "This is exocytosis: fusion releases cargo outward. On the sequence cradle, track where the cargo starts and ends.", "membrane");
    if (/pump|sodium|potassium/.test(text)) return lesson("An ion pump has an accounting cycle", "The sodium–potassium pump uses ATP to move sodium out and potassium in against their electrochemical gradients. Trace the cargo, direction, and energy source independently before connecting cycle labels.", ["Hypothetical training transporter, not the sodium–potassium pump: distinguish the outside from the cytoplasm before tracing its two colored ion streams.", "Our training transporter moves two positive ions outward and one inward using energy. Its accounting diagram therefore has unequal outgoing and incoming counts.", "The training exchange has a net outward movement of one positive charge. Its hypothetical counts do not specify the real apparatus's cycle: inspect that apparatus's own labels. A protein doorway alone does not imply active transport; energy use and uphill movement do."], "In a training diagram, a protein lets ions move down their electrochemical gradient without an energy input. Is that active transport?", ["Yes, every protein is a pump", "No, it is passive transport", "Yes, whenever ions move"], 1, "A channel can support passive transport. Check direction relative to the gradient and the energy source before labeling a transport mechanism.", "membrane");
    if (/diffusion|facilitated|active|energy|selectiv|transport|cargo/.test(text)) return lesson("Choose a route from cargo and conditions", "Small nonpolar molecules can diffuse through the lipid bilayer. Ions generally need a protein route. Passive transport moves down a concentration or electrochemical gradient; active transport uses energy to move against it.", ["Training cargo: oxygen is small and nonpolar. With more oxygen outside than inside, its net diffusion is inward through the bilayer.", "Training cargo: a charged ion cannot readily cross the hydrophobic core. A suitable channel lets it move down its electrochemical gradient without ATP directly driving that movement.", "To move cargo uphill, a transporter needs energy, directly or through coupling. First inspect cargo properties, then the gradient, then the route and energy source."], "A suitable protein moves a training molecule down its gradient without energy input. How should the sorter label it?", ["Active transport", "Facilitated diffusion", "Bulk transport"], 1, "Facilitated diffusion is passive even though a protein helps. Use cargo, gradient, and energy together when choosing the membrane port.", "membrane");
    return lesson("Inspect the boundary's architecture", "Phospholipids form a bilayer: water-loving heads face the aqueous fluid on either side, while water-avoiding tails face inward. This core helps make the boundary selective.", ["Training cross-section: identify water outside the cell and water in the cytoplasm. Both surfaces touch water.", "The heads face those two water compartments; the tails meet in the middle. The boundary is two layers rather than a solid wall.", "Transport proteins provide specialized routes through that boundary. A selective membrane admits different cargo in different ways."], "Which part of a phospholipid faces the watery cytoplasm?", ["Its hydrophobic tail", "Its hydrophilic head", "Neither part"], 1, "The hydrophilic head faces water on both sides of the bilayer. Use that structure when inspecting the maintenance plaques.", "membrane");
  }
  if (kind === "archive") {
    if (/source|provenance|primary|secondary|reliab|author/.test(text)) return lesson("Read a source before using its claim", "Source type and reliability are separate questions. Ask who made the source, when, for whom, and why; then compare its claim with independent evidence relevant to the question.", ["Invented practice record: a workshop attendance sheet lists 18 visitors. A later report says the workshop reached many residents. These are synthetic classroom examples, not historical evidence.", "The attendance sheet directly documents registered attendance, but cannot establish how every visitor felt. The later report offers an interpretation that needs support.", "Test a claim against what each source can actually establish. A contemporary source may have bias; a later study may use careful research. Provenance does not replace evaluation."], "A source was created during an event. What follows from that fact alone?", ["It is completely reliable", "It is necessarily unbiased", "It is contemporary, but still needs evaluation"], 2, "Contemporary origin identifies a relationship to the event, not guaranteed accuracy. On the evidence desk, inspect context and corroboration before accepting a claim.");
    if (/chronolog|date|timeline|sequence/.test(text)) return lesson("Order events before explaining them", "Chronology establishes before and after. Causation also needs a supported mechanism linking events; a later event is not automatically caused by an earlier one.", ["Invented practice timeline: a bridge inspection occurs Monday, a repair order Tuesday, and work begins Thursday. These records are synthetic, not historical sources.", "Sort by date first. The repair order explicitly references the inspection finding, supporting one connection between the first two events.", "The dates alone would not explain why work began Thursday. Look for evidence of decisions, resources, or other intervening developments before drawing a causal link."], "Two events happen in order. What would strengthen a causal link between them?", ["Evidence of the process connecting them", "Their dates alone", "A confident description"], 0, "A causal link needs a mechanism supported by evidence. On the timeline apparatus, establish the order; on a causal board, also justify the connections.");
    return lesson("Build a claim that survives its evidence", "Separate observation from interpretation. A sound explanation fits the supplied evidence and accounts for timing through supported intermediate links. A worksheet's answer key is not historical evidence.", ["Invented practice case: a reading room opens longer hours after a request and a staffing approval. All example records here are synthetic.", "The request supports demand for longer hours. The staffing approval supports the means to provide them. Neither alone proves why every visitor came.", "Compare explanations: the staffing change helps explain when hours could expand. A claim that ignores it leaves a gap. Check each link against the actual source material on your evidence board."], "A training explanation makes a claim that none of its records addresses. What is the best next move?", ["Treat the worksheet key as evidence", "Narrow the claim or seek relevant evidence", "Repeat the claim more confidently"], 1, "Narrow the claim to what the records support, or seek evidence that addresses it. Test claims against clues, preserve intermediate links, and distinguish the fictional guide story from source material.");
  }
  if (/slope|tangent/.test(text) || "samples" in view) return lesson("Measure steepness, not height", "Local slope describes change near a point: the tangent's rise divided by its run. A high point can have a nearly horizontal tangent.", ["Training terrain is y = x². At x = 0, its tangent is horizontal, even though this point is part of a curved landscape.", "At x = 2, the derivative 2x gives slope 4: the tangent rises 4 units per unit of horizontal run locally.", "The scanner's tangent estimates local change, not the elevation. If the task asks steepness, compare slope magnitudes; if it asks greatest slope, preserve the signs."], "A training hilltop has a horizontal tangent. What is its local slope?", ["Zero", "Its elevation", "Always the steepest slope"], 0, "A horizontal tangent has zero rise per horizontal run. Inspect the terrain scanner's tangent at the point, rather than selecting the highest point.");
  if (/equation|counterweight|algebra/.test(text)) return lesson("Keep the balance equivalent", "An equation asserts equal quantities. Apply the same valid operation to both sides to preserve equality and isolate the unknown.", ["Training balance: 3x + 6 = 21. Remove 6 from both pans: 3x = 15.", "Divide both sides by 3: x = 5. The three equal unknown weights together weighed 15.", "Check in the original: 3(5) + 6 = 21. Verification catches an operation applied to only one pan."], "To undo +4 in a training equation, which action preserves equality?", ["Subtract 4 from only the left", "Add 4 to only the right", "Subtract 4 from both sides"], 2, "Subtracting the same amount from both sides preserves equality. On the balance apparatus, apply equivalent operations before isolating the unknown.");
  if (/atom|reaction|chem/.test(text)) return lesson("Count atoms without changing substances", "Balance a chemical equation by changing coefficients, not subscripts. Each element must have the same atom count on both sides.", ["Training reaction: N₂ + H₂ → NH₃. The left has two nitrogen atoms; a single ammonia molecule has one.", "Use two ammonia molecules: N₂ + H₂ → 2NH₃. The right now has two nitrogen and six hydrogen atoms.", "Use three hydrogen molecules: N₂ + 3H₂ → 2NH₃. Both sides contain N: 2 and H: 6. The formulas remain unchanged."], "To supply six hydrogen atoms using H₂ molecules, what coefficient is needed?", ["6", "3", "2"], 1, "Three H₂ molecules contain 3 × 2 = 6 hydrogen atoms. Count each element on the atom-token mixer after each coefficient adjustment.");
  if (/ledger|budget|outflow|income/.test(text)) return lesson("Follow the resource ledger", "A ledger reconciles starting resources plus inflows minus outflows. The sign of an entry follows its role in the account.", ["Training account starts with $40. A $25 supply credit raises the available balance to $65.", "A $15 purchase is an outflow: $65 − $15 = $50. Recording it as income would double-count its direction.", "Reconcile the ending balance with every entry: $40 + $25 − $15 = $50. Keep starting balance, flow, and closing balance distinct."], "A training account receives $12 and spends $5. What is its net change?", ["+$17", "−$7", "+$7"], 2, "Net change is inflow minus outflow: 12 − 5 = +7. Follow the sign and role of each console entry.");
  if (/codon|mrna|translation/.test(text)) return lesson("Translate in ordered triplets", "Read mRNA as codons of three bases, preserving the stated reading frame and sequence order. Use the supplied codon table to map each triplet to an amino acid or stop signal.", ["Training mRNA: 5′–UUU GGU UAA–3′, with the reading frame already marked. Use the standard code for this worked example.", "UUU maps to phenylalanine; GGU maps to glycine; UAA is a stop signal. The peptide produced in this framed example is Phe–Gly.", "A stop signal terminates translation and is not an amino acid. On your reader, use its displayed mapping and framing, rather than regrouping the bases."], "A training reader already marks codons as ABC | DEF. What should you preserve when using its mapping?", ["Triplet boundaries and order", "Only alphabetical order", "Single-base groups"], 0, "Mapping changes representation while preserving sequence. Read each displayed triplet in order and follow the table's stop convention.");
  if (/trace|variable|instruction|program/.test(text) || "code" in view) return lesson("Track the controller's current state", "Assignment replaces the stored value. Execute each instruction in order, using current values when evaluating later expressions and branches.", ["Training program starts with x = 4. After x = x + 3, the stored value is 7.", "Next, x = 2 × x uses the current 7, so the stored value becomes 14. It does not reuse the original 4.", "A final print(x) emits 14. Keep a small state table after every update; inspect the program's indexing convention before tracing a list."], "Training state is n = 2; then n = n + 5; then n = n − 1. What is printed?", ["1", "6", "7"], 1, "The state changes 2 → 7 → 6. On the console, trace updates in execution order and evaluate each expression with the current state.");
  if (/function|input.output|transformation/.test(text)) return lesson("Test a function against every example", "A function applies a consistent transformation. Several input–output pairs constrain a proposed rule; one pair alone can fit many rules.", ["Training pairs: 1 → 5, 2 → 8, 3 → 11. Equal input steps produce output steps of 3.", "Try f(x) = 3x + 2. Check all pairs: 3(1)+2=5; 3(2)+2=8; 3(3)+2=11.", "This rule predicts f(4) = 14. It fits these examples; unless a rule family is specified, finitely many pairs do not prove the rule is unique."], "A proposed training rule fits one pair but fails another. What should the tester do?", ["Use the first pair only", "Average the outputs", "Reject that rule and test another"], 2, "A consistent rule must fit every supplied pair. Use the bench examples to constrain the rule before predicting a new output.");
  const ordering = current.mode.widget === "order" || "steps" in view || "planks" in view;
  return lesson(ordering ? "Build a process with reasons" : "Connect the concept to the control", chapter.discovery.replace(/^[^:]+:\s*/, ""), ordering ? ["Training repair: inspect an unplugged lamp before choosing a repair. Observation establishes what needs to change.", "Reconnect its power lead before switching it on. The dependency gives a reason for this order, beyond remembering a sequence.", "Finally verify the lamp lights. On your sequence apparatus, ask what each step enables and separate any step that belongs to another process."] : ["Training control: an instrument shows a quantity, a scale, and a setting. Read which quantity the task asks you to change before adjusting anything.", "Change one setting and observe the result. Distinguish the measured property from a nearby property that may look similar.", "For a classification, compare the case against the category definition; for a missing term, read the surrounding relationship. Use the chapter principle to explain the decision."], ordering ? "A training action requires power. Where should connecting power go?" : "A training setting changes height, while the task asks repeat time. What should you inspect next?", ordering ? ["Before the action that requires it", "After the final verification", "Anywhere in the sequence"] : ["The height only", "The quantity and control for repetition", "The most prominent label"], ordering ? 0 : 1, ordering ? "Dependencies justify the order. On your apparatus, place each prerequisite before the step that uses it." : "Match the control to the requested property. Use the stated relationship and displayed units to justify your choice.");
}

export function LearningStudio(props: LearningStudioProps) {
  // Encounter identity resets local learning state even when the host reuses this component.
  return <StudioSession key={`${props.kind}-${props.current.index}-${props.chapter.id}`} {...props} />;
}

function StudioSession({ kind, current, chapter, guidance, onDone }: LearningStudioProps) {
  const content = chooseLesson(kind, current, chapter);
  const [phase, setPhase] = useState<"show" | "predict">("show");
  const [step, setStep] = useState(0);
  const [choice, setChoice] = useState<number | null>(null);
  const titleId = useId();
  const supported = guidance === "supported";
  if (guidance === "independent") return <section className={`learning-studio ls-${kind}`} aria-labelledby={titleId} data-testid="learning-studio">
    <div className="ls-heading"><span className="ls-eyebrow">FIELD TRAINING · {String(current.index + 1).padStart(2, "0")}</span><span className="ls-guidance">Independent application</span></div>
    <h2 id={titleId}>You have this relationship.</h2>
    <p className="ls-purpose"><strong>Your apparatus: {chapter.apparatus}.</strong> {chapter.objective}</p>
    <p>You have solved the recent field operations cleanly on your first try without a hint. Take this new situation directly to its controls; ask your companion for support at any point.</p>
    <div className="ls-actions"><button className="ls-primary" onClick={onDone}>Start the field operation →</button></div>
  </section>;
  return <section className={`learning-studio ls-${kind}`} aria-labelledby={titleId} data-testid="learning-studio">
    <div className="ls-heading"><span className="ls-eyebrow">FIELD TRAINING · {String(current.index + 1).padStart(2, "0")}</span><span className="ls-guidance">{supported ? "Guided walkthrough" : guidance === "light" ? "Quick refresher" : "Independent exploration"}</span></div>
    <h2 id={titleId}>{content.title}</h2>
    <p className="ls-purpose"><strong>Your apparatus: {chapter.apparatus}.</strong> {chapter.objective}</p>
    <div className="ls-phases" aria-label="Learning stages"><span aria-current={phase === "show" ? "step" : undefined}>1 · Show me</span><span aria-current={phase === "predict" ? "step" : undefined}>2 · Your turn</span><span>3 · Use the apparatus</span></div>
    {phase === "show" ? <>
      <p className="ls-principle">{content.principle}</p>
      <div className="ls-example-label">Worked example · separate training setup</div>
      {content.visual === "circle" ? <CircleLab /> : content.visual === "wave" ? <WaveLab /> : content.visual === "membrane" ? <MembraneLab /> : <ProcessDiagram steps={content.steps} active={step} onSelect={setStep} />}
      <div className="ls-worked"><div className="ls-step-tabs" aria-label="Worked example steps">{content.steps.map((_, index) => <button key={index} aria-pressed={step === index} onClick={() => setStep(index)}>Step {index + 1}</button>)}</div><p aria-live="polite">{content.steps[step]}</p></div>
      {supported && <p className="ls-scaffold">Observe → explain → predict. Try changing a single control or tracing one step, then describe what changed before moving on.</p>}
      <div className="ls-actions"><button className="ls-primary" onClick={() => { setPhase("predict"); setChoice(null); }}>Try a guided prediction →</button></div>
    </> : <>
      <p className="ls-example-label">Your turn · practice the principle</p><h3>{content.prediction}</h3>
      <details open={supported}><summary>Thinking scaffold</summary><p>{content.principle}</p><p>Identify what changes, what stays fixed, and the relationship that connects them.</p></details>
      <div className="ls-choices" aria-label="Prediction choices">{content.choices.map((label, index) => <button key={label} aria-pressed={choice === index} onClick={() => setChoice(index)}>{label}</button>)}</div>
      <div className="ls-feedback" aria-live="polite" aria-atomic="true">{choice !== null && <><strong>{choice === content.correct ? "That follows the principle." : "Let's work through that prediction."}</strong><p>{choice !== content.correct && <>The supported prediction is <b>{content.choices[content.correct]}</b>. </>}{content.explanation}</p><p>Take this reasoning to {chapter.apparatus.toLowerCase()} and inspect its own presented conditions.</p></>}</div>
      <p className="ls-note">This training prediction does not affect your mission score. A correction is part of learning; you can continue after reviewing it.</p>
      <div className="ls-actions"><button className="ls-secondary" onClick={() => setPhase("show")}>Revisit the worked example</button><button className="ls-primary" disabled={choice === null} onClick={onDone}>Use the apparatus →</button></div>
    </>}
  </section>;
}

function CircleLab() {
  const [degrees, setDegrees] = useState(150);
  const id = useId();
  const angle = degrees * Math.PI / 180;
  const x = Math.cos(angle), y = Math.sin(angle);
  const px = 150 + x * 98, py = 135 - y * 98;
  const normalized = degrees % 360;
  const reference = normalized <= 90 ? normalized : normalized <= 180 ? 180 - normalized : normalized <= 270 ? normalized - 180 : 360 - normalized;
  const move = (event: PointerEvent<SVGSVGElement>) => {
    const bounds = event.currentTarget.getBoundingClientRect();
    // Preserve the SVG's aspect ratio when translating pointer coordinates.
    const scale = Math.min(bounds.width / 300, bounds.height / 270);
    const dx = (event.clientX - bounds.left - (bounds.width - 300 * scale) / 2) / scale - 150;
    const dy = 135 - (event.clientY - bounds.top - (bounds.height - 270 * scale) / 2) / scale;
    setDegrees(Math.round((Math.atan2(dy, dx) * 180 / Math.PI + 360) % 360));
  };
  return <div className="ls-lab"><svg className="ls-circle" viewBox="0 0 300 270" role="img" aria-label={`Unit-circle arm at ${degrees} degrees. Horizontal coordinate ${x.toFixed(2)}, vertical coordinate ${y.toFixed(2)}. Drag or use the angle slider.`} onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); move(event); }} onPointerMove={event => { if (event.currentTarget.hasPointerCapture(event.pointerId)) move(event); }}>
    <circle cx="150" cy="135" r="98" className="ls-circle-rim"/><line x1="25" y1="135" x2="275" y2="135" className="ls-axis"/><line x1="150" y1="14" x2="150" y2="252" className="ls-axis"/>
    <path d={`M150,135 L${px},135 L${px},${py} Z`} className="ls-triangle"/><line x1="150" y1="135" x2={px} y2={py} className="ls-arm"/><circle cx={px} cy={py} r="6" className="ls-probe"/>
    <text x="263" y="153">x</text><text x="161" y="24">y</text><text x="255" y="123">0°</text><text x="157" y="43">90°</text><text x="16" y="123">180°</text><text x="158" y="245">270°</text>
  </svg><div className="ls-lab-controls"><label htmlFor={id}>Rotate the training arm <output>{degrees}°</output></label><input id={id} type="range" min="0" max="360" step="1" value={degrees} onChange={event => setDegrees(Number(event.target.value))}/><div className="ls-readouts"><span>θ <b>{angle.toFixed(3)} rad</b></span><span>cos θ · horizontal <b>{x.toFixed(3)}</b></span><span>sin θ · vertical <b>{y.toFixed(3)}</b></span><span>Reference angle <b>{reference}°</b></span></div><p>Radius 1: arc length = θ. Radius 2: arc length = {(2 * angle).toFixed(3)}. The angle stays the same.</p><p>The reference angle is the smallest angle to the horizontal axis. It gives coordinate magnitudes; the quadrant determines their signs.</p></div></div>;
}

function WaveLab() {
  const [a, setA] = useState(2), [b, setB] = useState(1), [c, setC] = useState(0), [d, setD] = useState(1), [time, setTime] = useState(0);
  const id = useId();
  const tau = Math.PI * 2;
  const sx = (t: number) => 42 + t / (tau * 2) * 460;
  const sy = (value: number) => 130 - value * 17;
  const value = (t: number) => a * Math.sin(b * t + c) + d;
  const path = Array.from({ length: 601 }, (_, i) => `${i ? "L" : "M"}${sx(i / 600 * tau * 2).toFixed(2)},${sy(value(i / 600 * tau * 2)).toFixed(2)}`).join(" ");
  return <div className="ls-wave"><p className="ls-formula">y = {a} sin({b}t {c < 0 ? "−" : "+"} {Math.abs(c).toFixed(2)}) {d < 0 ? "−" : "+"} {Math.abs(d)}</p><svg viewBox="0 0 540 265" role="img" aria-label={`Training sine graph. Amplitude ${a}, period ${(tau / b).toFixed(2)}, midline ${d}, phase shift ${(-c / b).toFixed(2)}. At time ${time.toFixed(2)}, value ${value(time).toFixed(2)}.`}>
    {[-6, -3, 0, 3, 6].map(y => <g key={y}><line x1="42" y1={sy(y)} x2="502" y2={sy(y)} className="ls-grid"/><text x="31" y={sy(y)+4} textAnchor="end">{y}</text></g>)}
    {[0, 1, 2, 3, 4].map(i => <g key={i}><line x1={sx(i*Math.PI)} y1="23" x2={sx(i*Math.PI)} y2="237" className="ls-grid"/><text x={sx(i*Math.PI)} y="255" textAnchor="middle">{i === 0 ? "0" : `${i === 1 ? "" : i}π`}</text></g>)}
    <line x1="42" y1={sy(0)} x2="502" y2={sy(0)} className="ls-axis"/><line x1="42" y1={sy(d)} x2="502" y2={sy(d)} className="ls-midline"/><path d={path} className="ls-wave-path"/><line x1={sx(time)} y1="23" x2={sx(time)} y2="237" className="ls-cursor"/><circle cx={sx(time)} cy={sy(value(time))} r="5" className="ls-probe"/><text x="515" y="255">t</text><text x="17" y="15">y</text>
  </svg><div className="ls-wave-dials">{[{key:"A",label:"A · swing height",value:a,set:setA,min:.5,max:4,step:.5},{key:"b",label:"b · repetition rate",value:b,set:setB,min:.5,max:3,step:.5},{key:"c",label:"c · phase angle",value:c,set:setC,min:-Math.PI,max:Math.PI,step:Math.PI/12},{key:"d",label:"d · midline",value:d,set:setD,min:-2,max:2,step:.5},{key:"t",label:"t · time probe",value:time,set:setTime,min:0,max:tau*2,step:.05}].map(control => <div key={control.key}><label htmlFor={`${id}-${control.key}`}>{control.label}<output>{control.value.toFixed(2)}</output></label><input id={`${id}-${control.key}`} type="range" min={control.min} max={control.max} step={control.step} value={control.value} onChange={event => control.set(Number(event.target.value))}/></div>)}</div><div className="ls-readouts"><span>Amplitude <b>{a}</b></span><span>Period <b>{(tau/b).toFixed(3)}</b></span><span>Phase shift <b>{(-c/b).toFixed(3)}</b></span><span>At t = {time.toFixed(2)} <b>y = {value(time).toFixed(3)}</b></span></div><p>The dashed line is the midline. Native sliders support dragging and arrow keys. Change one parameter at a time and compare the trace.</p></div>;
}

function MembraneLab() {
  const [protein, setProtein] = useState(false);
  return <div className="ls-membrane"><svg viewBox="0 0 540 180" role="img" aria-label={`Bilayer cross-section: hydrophilic heads face water, hydrophobic tails point inward. ${protein ? "A protein channel spans the bilayer." : "Small nonpolar cargo crosses the lipid route."}`}><text x="18" y="24">Outside · water</text><text x="18" y="164">Cytoplasm · water</text>{Array.from({length:18},(_,i) => <g key={i}><circle cx={20+i*29} cy="62" r="8" className="ls-lipid"/><path d={`M${17+i*29},70 v22 M${23+i*29},70 v22 M${17+i*29},110 v-15 M${23+i*29},110 v-15`} className="ls-tail"/><circle cx={20+i*29} cy="118" r="8" className="ls-lipid"/></g>)}{protein && <rect x="255" y="47" width="40" height="86" rx="12" className="ls-channel"/>}<path d={protein ? "M275,29 V147" : "M390,29 V147"} className="ls-cargo-path"/><text x="315" y="41">{protein ? "Protein route" : "Lipid route"}</text></svg><div className="ls-step-tabs"><button aria-pressed={!protein} onClick={() => setProtein(false)}>Inspect lipid route</button><button aria-pressed={protein} onClick={() => setProtein(true)}>Reveal protein route</button></div><p>{protein ? "A protein crosses the hydrophobic core. Whether a pathway is passive or active also depends on gradient direction and energy use." : "The heads face the water on both surfaces. The tails form a hydrophobic core. Small nonpolar molecules can diffuse through it."}</p></div>;
}

function ProcessDiagram({ steps, active, onSelect }: { steps: Lesson["steps"]; active: number; onSelect(index: number): void }) {
  return <div className="ls-process" aria-label="Interactive worked example">{steps.map((text, index) => <button key={text} onClick={() => onSelect(index)} aria-pressed={index === active}><span className="ls-process-number">{String(index+1).padStart(2,"0")}</span><strong>{["Observe the setup", "Apply the relationship", "Check what follows"][index]}</strong><span>{text}</span></button>)}</div>;
}
