// GENERATED by scripts/build-art.ts (pnpm art:build --ns archive_of_voices). Do not edit by hand.
// 0 entries from public/assets/expedition/archive_of_voices/manifest.json.
import type { AssetIndex } from "./types";

export const ASSET_INDEX_ARCHIVE_OF_VOICES: AssetIndex = {};
