// GENERATED by scripts/build-art.ts (pnpm art:build --ns living_gate). Do not edit by hand.
// 0 entries from public/assets/expedition/living_gate/manifest.json.
import type { AssetIndex } from "./types";

export const ASSET_INDEX_LIVING_GATE: AssetIndex = {};
