// GENERATED by scripts/build-art.ts (pnpm art:build --ns orrery_terraces). Do not edit by hand.
// Empty until the art pipeline (A1/A2) writes this namespace's manifest.
import type { AssetIndex } from "./types";

export const ASSET_INDEX_ORRERY_TERRACES: AssetIndex = {};
