// GENERATED by scripts/build-art.ts (pnpm art:build --ns orrery_terraces). Do not edit by hand.
// 0 entries from public/assets/expedition/orrery_terraces/manifest.json.
import type { AssetIndex } from "./types";

export const ASSET_INDEX_ORRERY_TERRACES: AssetIndex = {};
