// GENERATED by scripts/build-art.ts (pnpm art:build --ns shared). Do not edit by hand.
// 6 entries from public/assets/expedition/shared/manifest.json.
import type { AssetIndex } from "./types";

export const ASSET_INDEX_SHARED: AssetIndex = {
  "shared.char.diver": { ns: "shared", kind: "atlas", width: 168, height: 224, anchors: {}, source: "rig:female_adventurer", zone: "all", poses: ["idle","walk0","walk1","walk2","walk3","walk4","walk5","walk6","walk7","run0","run1","run2","jump","fall","duck","hang","climb0","climb1","interact","switch0","switch1","talk","think","show","hold","cheer0","cheer1","back"] },
  "shared.char.ida": { ns: "shared", kind: "atlas", width: 168, height: 224, anchors: {}, source: "rig:female_person", zone: "all", poses: ["idle","walk0","walk2","walk4","walk6","talk","think","show","interact","cheer0","duck","hold"] },
  "shared.char.nell": { ns: "shared", kind: "atlas", width: 168, height: 224, anchors: {}, source: "rig:female_adventurer", zone: "all", poses: ["idle","walk0","walk1","walk2","walk3","walk4","walk5","walk6","walk7","run0","run1","run2","jump","fall","duck","hang","climb0","climb1","interact","switch0","switch1","talk","think","show","hold","cheer0","cheer1","back"] },
  "shared.char.otis": { ns: "shared", kind: "atlas", width: 168, height: 224, anchors: {}, source: "rig:male_person", zone: "all", poses: ["idle","walk0","walk2","walk4","walk6","talk","think","show","interact","cheer0","duck","hold"] },
  "shared.char.wren": { ns: "shared", kind: "atlas", width: 168, height: 224, anchors: {}, source: "rig:female_adventurer", zone: "all", poses: ["idle","walk0","walk1","walk2","walk3","walk4","walk5","walk6","walk7","run0","run1","run2","jump","fall","duck","hang","climb0","climb1","interact","switch0","switch1","talk","think","show","hold","cheer0","cheer1","back"] },
  "shared.companion.guide_standin": { ns: "shared", kind: "puppet", width: 72, height: 72, anchors: {}, source: "kit:companionStandin", zone: "all", anims: ["idle","talk","cue"] },
};
