/**
 * src/game/art/palettes/archive_of_voices.ts — W0 seed (docs/design/20 §5.7; bible §2.1; civil §2.2). Owned by C0 then
 * C3. Orange never appears in this world except on the Record Lens chip and aimed/accused sockets (bound to input).
 */
export const ARCHIVE_OF_VOICES_PALETTE = {
  namespace: "archive_of_voices",
  tokens: {
    // ---- bible §2.1 world base
    "stone.lit": "#FBF1DE",
    "stone.base": "#F2E3C6",
    "stone.shade": "#D9C3A0",
    "stone.deep": "#B89C78",
    "sand.path": "#EBCFAE",
    "gold.hi": "#F6D27A",
    "gold.base": "#D9A441",
    "gold.deep": "#A8782E",
    "inlay.navy": "#27466A",
    "inlay.navy.dark": "#1B3150",
    "bronze.ring": "#6E4A2E",
    "rock.light": "#8FA6A0",
    "rock.base": "#5F7B7A",
    "rock.shade": "#3F5857",
    "grass.light": "#9ED6C4",
    "grass.base": "#6FB7A6",
    "grass.shade": "#4F8F85",
    "water.shallow": "#8FE0EA",
    "water.deep": "#4CB6D0",
    "crystal.hi": "#C9F3FF",
    "crystal.base": "#6ED2F2",
    "crystal.shade": "#2E8FC0",
    "foliage.blue": "#5A95D6",
    "foliage.blue.hi": "#8CC0EE",
    "foliage.salmon": "#E48C5E",
    "foliage.salmon.hi": "#F4AE80",
    "foliage.rust": "#C4643C",
    "wisp.indigo": "#6A6CF0",
    "shadow": "#6E7F9A",
    "haze": "#F6D9BE",
    // ---- civil tokens (civil §2.2)
    "brick.lit": "#D08A6E",
    "brick.base": "#B5654F",
    "brick.shade": "#7E4038",
    "brick.dusk": "#8E5A6A",
    "brick.dusk.lit": "#B07A86",
    "brass.hi": "#F6D27A",
    "brass.base": "#D9A441",
    "brass.deep": "#A8782E",
    "concrete": "#B9AFC6",
    "curb": "#8C829E",
    "asphalt.wet": "#4A4F66",
    "asphalt.sheen": "#6D6F8C",
    "steel": "#9AA3B8",
    "steel.shade": "#646C85",
    "oak.leaf": "#5A95D6",
    "oak.leaf.hi": "#8CC0EE",
    "magnolia": "#3E5F74",
    "magnolia.hi": "#6E93A6",
    "autumn": "#E48C5E",
    "autumn.hi": "#F4AE80",
    "recordlight": "#6ED2F2",
    "recordlight.hi": "#C9F3FF",
    "recordlight.shade": "#2E8FC0",
    "dormant": "#A9A3B8",
    "lamp": "#F6D27A",
    "safelight": "#C4643C",
    "paper": "#F7F1E3",
    "paper.aged": "#E9D8B4",
    "paper.trap": "#D9C08E",
    "ink": "#2B3A44",
    // ---- skies (civil §2.3)
    "sky.late_afternoon.top": "#B9A3D6",
    "sky.late_afternoon.horizon": "#F6D9BE",
    "sky.dusk_rain.top": "#7F6BB8",
    "sky.dusk_rain.horizon": "#E8A9C3",
    "sky.blue_hour.top": "#3E3F74",
    "sky.blue_hour.horizon": "#C58BB0",
    "sky.interior.top": "#3B2F3E",
    "sky.interior.horizon": "#5E4A4A",
  } as Readonly<Record<string, string>>,
} as const;
