/**
 * src/game/art/palettes/living_gate.ts — W0 seed, completed by C0 from cell §2.2, §3.1 and 02 §3b.4; C2 added the
 * hero tokens (nucleus dome, hall vault, Ora, Poro, the Mimic Mote, the Halcyon) from cell §7.
 * Owned by C2 from T0 + 6.5 (docs/design/20 §7.3).
 * No pure black: the darkest colours are lifted (#433748, #27405F, inlay.navy.dark #22385A) per cell §2.2.
 */
export const LIVING_GATE_PALETTE = {
  namespace: "living_gate",
  tokens: {
    // ---- bible §2.1 world base
    "stone.lit": "#FBF1DE",
    "stone.base": "#F2E3C6",
    "stone.shade": "#D9C3A0",
    "stone.deep": "#B89C78",
    "sand.path": "#EBCFAE",
    "gold.hi": "#F6D27A",
    "gold.base": "#D9A441",
    "gold.deep": "#A8782E",
    "inlay.navy": "#27466A",
    "inlay.navy.dark": "#22385A", // lifted from the bible's #1B3150 (cell §2.2)
    "bronze.ring": "#6E4A2E",
    "rock.light": "#8FA6A0",
    "rock.base": "#5F7B7A",
    "rock.shade": "#3F5857",
    "grass.light": "#9ED6C4",
    "grass.base": "#6FB7A6",
    "grass.shade": "#4F8F85",
    "water.shallow": "#8FE0EA",
    "water.deep": "#4CB6D0",
    "crystal.hi": "#C9F3FF",
    "crystal.base": "#6ED2F2",
    "crystal.shade": "#2E8FC0",
    "foliage.blue": "#5A95D6",
    "foliage.blue.hi": "#8CC0EE",
    "foliage.salmon": "#E48C5E",
    "foliage.salmon.hi": "#F4AE80",
    "foliage.rust": "#C4643C",
    "wisp.indigo": "#6A6CF0",
    "shadow": "#6E7F9A",
    "haze": "#FFFFFF",
    // ---- cell tokens (cell §2.2)
    "lipid.head.lit": "#FBF1DE",
    "lipid.head": "#F2E3C6",
    "lipid.head.shade": "#D9C3A0",
    "lipid.tail.hi": "#F6D27A",
    "lipid.tail": "#D9A441",
    "lipid.tail.deep": "#A8782E",
    "oil.seam": "#27466A",
    "oil.seam.dark": "#27405F",
    "protein.stone": "#F2E3C6",
    "protein.stone.shade": "#D9C3A0",
    "protein.ring": "#6E4A2E",
    "gel.frost": "#DCE8EA",
    "glycan.blue": "#5A95D6",
    "glycan.blue.hi": "#8CC0EE",
    "glycan.salmon": "#E48C5E",
    "glycan.salmon.hi": "#F4AE80",
    "glycan.rust": "#C4643C",
    "cholesterol.hi": "#C9F3FF",
    "cholesterol.base": "#6ED2F2",
    "cholesterol.shade": "#2E8FC0",
    "tide.shallow": "#8FE0EA",
    "tide.deep": "#4CB6D0",
    "cyto.glow": "#F6C48E",
    "cyto.deep": "#D98A6A",
    "mito.coral": "#E7836F",
    "atp.gold": "#F6D27A",
    "atp.gold.core": "#FFF6D8",
    "hall.ceiling": "#433748",
    "oil.seam.shadow": "#22385A",
    // ---- molecule colours (cell §2.2; fixed across world and panel)
    "mol.o2": "#8CC0EE",
    "mol.co2": "#A9C3BF",
    "mol.na": "#EE8A9A",
    "mol.k": "#9C82E0",
    "mol.cl": "#7FD6B0",
    "mol.h": "#F7F0A0",
    "mol.glucose": "#F6E3B4",
    "mol.glucose.outline": "#D9A441",
    "mol.steroid": "#E6B85C",
    "mol.water": "#4F92E6",
    "mol.dye": "#D46BA8",
    "mol.salt": "#FFFFFF",
    "mol.atp": "#F6D27A",
    "mol.atp.core": "#FFFFFF",
    // ---- rig recolour (cell §3.1, 02 §3b.4 Diver column; roles → char.<id>.<role>)
    "char.diver.skin": "#C68B5E",
    "char.diver.skinShade": "#A06E48",
    "char.diver.hair": "#3A2A24",
    "char.diver.hairHi": "#5A3E32",
    "char.diver.ink": "#2B2A33",
    "char.diver.band": "#3A2A24",
    "char.diver.top": "#F2E3C6",
    "char.diver.topMid": "#E6D5B5",
    "char.diver.topShade": "#D9C3A0",
    "char.diver.sleeve": "#F2E3C6",
    "char.diver.sleeveShade": "#D9C3A0",
    "char.diver.bottom": "#27466A",
    "char.diver.sock": "#27466A",
    "char.diver.boots": "#6E4A2E",
    "char.diver.strap": "#A8782E",
    // ---- costume overlays (cell §3.1)
    "costume.diver.helmet": "#C9F3FF",
    "costume.diver.helmet.ring": "#D9A441",
    "costume.diver.scarf": "#4CB6D0",
    "costume.diver.scarf.stripe": "#8FE0EA",
    "costume.diver.valve": "#27466A",
    // ---- C2 hero tokens (cell §7.2–§7.9)
    "nucleus.dome": "#C98BB0",
    "nucleus.dome.lit": "#E2B3CC",
    "nucleus.dome.shade": "#A56F93",
    "nucleus.rim": "#F4DCE8",
    "hall.wall": "#4E3C44",
    "hall.wall.lit": "#624B52",
    "hall.wall.shade": "#433748",
    "hall.glass": "#F6C48E",
    "mote.jelly": "#E8F6F8",
    "mote.jelly.shade": "#B9D9DE",
    "mote.eye": "#27466A",
    "glass.tint": "#C9F3FF",
    "cell.cyto": "#F6C48E",
    "cell.nucleus": "#C98BB0",
    "gel.frost.lit": "#F4FAFB",
    "gel.frost.shade": "#AFC6CC",
    "char.ora.skin": "#9A6444",
    "char.ora.skinShade": "#7A4C33",
    "char.ora.hair": "#3A2A24",
    "char.ora.hairHi": "#5A3E32",
    "char.ora.suit": "#4CB6D0",
    "char.ora.suitShade": "#3A93AB",
    "char.ora.lip": "#6B3A2A",
    "poro.water": "#8FE0EA",
  } as Readonly<Record<string, string>>,
} as const;
