/**
 * src/game/art/palettes/living_gate.ts — W0 seed (docs/design/20 §5.7; bible §2.1; cell §2.2). Owned by C0 then C2.
 * No pure black: the darkest colours are lifted (#433748, #27405F) per cell §2.2.
 */
export const LIVING_GATE_PALETTE = {
  namespace: "living_gate",
  tokens: {
    // ---- bible §2.1 world base
    "stone.lit": "#FBF1DE",
    "stone.base": "#F2E3C6",
    "stone.shade": "#D9C3A0",
    "stone.deep": "#B89C78",
    "sand.path": "#EBCFAE",
    "gold.hi": "#F6D27A",
    "gold.base": "#D9A441",
    "gold.deep": "#A8782E",
    "inlay.navy": "#27466A",
    "inlay.navy.dark": "#1B3150",
    "bronze.ring": "#6E4A2E",
    "rock.light": "#8FA6A0",
    "rock.base": "#5F7B7A",
    "rock.shade": "#3F5857",
    "grass.light": "#9ED6C4",
    "grass.base": "#6FB7A6",
    "grass.shade": "#4F8F85",
    "water.shallow": "#8FE0EA",
    "water.deep": "#4CB6D0",
    "crystal.hi": "#C9F3FF",
    "crystal.base": "#6ED2F2",
    "crystal.shade": "#2E8FC0",
    "foliage.blue": "#5A95D6",
    "foliage.blue.hi": "#8CC0EE",
    "foliage.salmon": "#E48C5E",
    "foliage.salmon.hi": "#F4AE80",
    "foliage.rust": "#C4643C",
    "wisp.indigo": "#6A6CF0",
    "shadow": "#6E7F9A",
    "haze": "#FFFFFF",
    // ---- cell tokens (cell §2.2)
    "lipid.head.lit": "#FBF1DE",
    "lipid.head": "#F2E3C6",
    "lipid.head.shade": "#D9C3A0",
    "lipid.tail.hi": "#F6D27A",
    "lipid.tail": "#D9A441",
    "lipid.tail.deep": "#A8782E",
    "oil.seam": "#27466A",
    "oil.seam.dark": "#27405F",
    "protein.stone": "#F2E3C6",
    "protein.stone.shade": "#D9C3A0",
    "protein.ring": "#6E4A2E",
    "gel.frost": "#DCE8EA",
    "glycan.blue": "#5A95D6",
    "glycan.blue.hi": "#8CC0EE",
    "glycan.salmon": "#E48C5E",
    "glycan.salmon.hi": "#F4AE80",
    "glycan.rust": "#C4643C",
    "cholesterol.hi": "#C9F3FF",
    "cholesterol.base": "#6ED2F2",
    "cholesterol.shade": "#2E8FC0",
    "tide.shallow": "#8FE0EA",
    "tide.deep": "#4CB6D0",
    "cyto.glow": "#F6C48E",
    "cyto.deep": "#D98A6A",
    "mito.coral": "#E7836F",
    "atp.gold": "#F6D27A",
    "atp.gold.core": "#FFF6D8",
    "hall.ceiling": "#433748",
    // ---- molecule colours (cell §2.2; fixed across world and panel)
    "mol.o2": "#8CC0EE",
    "mol.co2": "#A9C3BF",
    "mol.na": "#EE8A9A",
  } as Readonly<Record<string, string>>,
} as const;
