/**
 * src/game/art/palettes/orrery_terraces.ts — W0 seed, completed by C0 from trig §2.2–§2.4, §3.1 and 02 §3b.4 (rig roles).
 * Owned by C1 from T0 + 6 (docs/design/20 §7.3). Token path → colour; hero SVGs and kit params reference `{{token.path}}`.
 */
export const ORRERY_TERRACES_PALETTE = {
  namespace: "orrery_terraces",
  tokens: {
    // ---- bible §2.1 world base
    "stone.lit": "#FBF1DE",
    "stone.base": "#F2E3C6",
    "stone.shade": "#D9C3A0",
    "stone.deep": "#B89C78",
    "sand.path": "#EBCFAE",
    "gold.hi": "#F6D27A",
    "gold.base": "#D9A441",
    "gold.deep": "#A8782E",
    "inlay.navy": "#27466A",
    "inlay.navy.dark": "#1B3150",
    "bronze.ring": "#6E4A2E",
    "rock.light": "#8FA6A0",
    "rock.base": "#5F7B7A",
    "rock.shade": "#3F5857",
    "grass.light": "#9ED6C4",
    "grass.base": "#6FB7A6",
    "grass.shade": "#4F8F85",
    "water.shallow": "#8FE0EA",
    "water.deep": "#4CB6D0",
    "crystal.hi": "#C9F3FF",
    "crystal.base": "#6ED2F2",
    "crystal.shade": "#2E8FC0",
    "foliage.blue": "#5A95D6",
    "foliage.blue.hi": "#8CC0EE",
    "foliage.salmon": "#E48C5E",
    "foliage.salmon.hi": "#F4AE80",
    "foliage.rust": "#C4643C",
    "wisp.indigo": "#6A6CF0",
    "shadow": "#6E7F9A",
    "haze": "#FFFFFF",
    // ---- skies (bible §2.2; trig §2.3)
    "sky.day.top": "#D8D4CF",
    "sky.day.mid": "#E8DCD2",
    "sky.day.horizon": "#F4E7DA",
    "sky.peach.top": "#E9C9C0",
    "sky.peach.mid": "#F2D8C8",
    "sky.peach.horizon": "#FAE9D8",
    "sky.dusk.top": "#9E86D8",
    "sky.dusk.mid": "#C9A0DE",
    "sky.dusk.horizon": "#F2B8D4",
    // ---- trig tokens (trig §2.2)
    "orrery.beam": "#6ED2F2",
    "orrery.beam.core": "#FFFFFF",
    "orrery.brass": "#C99A4A",
    "orrery.brass.hi": "#EBC57A",
    "orrery.brass.deep": "#8E6428",
    "orrery.engrave": "#B89C78",
    "orrery.fog": "#EDE6F2",
    "vesper.star": "#FFF4D6",
    "vesper.star.glow": "#F6D27A",
    "dome.violet": "#5B4B8A",
    "dome.violet.mid": "#7E6A9E",
    "dome.violet.hi": "#B7A2D9",
    "sky.dusk.low": "#F7C9B8",
    "sky.dome.top": "#5B4B8A",
    "sky.dome.mid": "#7E6A9E",
    "sky.dome.horizon": "#B7A2D9",
    // ---- per-zone far colours and dressing (trig §2.4, §7)
    "mesa.z1": "#8FA6A0",
    "mesa.z2": "#C9A99E",
    "mesa.z3": "#7E6A9E",
    "cloud.underside": "#E6DDEA",
    "pollen": "#FFF4D6",
    "crystal.trunk": "#B7C4C8",
    "canal.slate": "#0F2A33",
    "cog.eye": "#6ED2F2",
    // ---- rig recolour (02 §3b.4 Wren column; roles → char.<id>.<role>)
    "char.wren.skin": "#A8714F",
    "char.wren.skinShade": "#8A5A3E",
    "char.wren.hair": "#2B2A33",
    "char.wren.hairHi": "#3A3945",
    "char.wren.ink": "#2B2A33",
    "char.wren.band": "#2B2A33",
    "char.wren.top": "#27466A",
    "char.wren.topMid": "#22405F",
    "char.wren.topShade": "#1B3150",
    "char.wren.sleeve": "#F2E3C6",
    "char.wren.sleeveShade": "#D9C3A0",
    "char.wren.bottom": "#2F5A5E",
    "char.wren.sock": "#2F5A5E",
    "char.wren.boots": "#C69A6B",
    "char.wren.strap": "#8A5A3E",
    // ---- costume overlays (trig §3.1)
    "costume.wren.scarf": "#4FA3A0",
    "costume.wren.scarf.hi": "#7CC7C0",
    "costume.wren.scarf.deep": "#357F7C",
    "costume.wren.staff": "#C99A4A",
    "costume.wren.hair": "#2B2A33",
    "costume.wren.hair.hi": "#4A4856",
    "leather": "#8A5A3E",
    "leather.hi": "#A8714F",
    "leather.deep": "#6A4430",
    // ---- C1 zone-1 heroes (trig §3.2, §3.3, §7.10, §7.13): recesses, glass, Brasswick's copper and moss
    "recess": "#2B3A44",
    "recess.hi": "#3F5857",
    "glass": "#DDF4F7",
    "copper": "#C07A48",
    "copper.hi": "#E09A66",
    "copper.deep": "#8A4E2E",
    "moss": "#7FA86A",
    "moss.hi": "#A6C98A",
    "moss.deep": "#557A4E",
    "tread": "#4A5560",
  } as Readonly<Record<string, string>>,
} as const;
